### ISSUE TITLE
User review url does not work

### ISSUE THREAD

**Issue by marcofucci** [uktrade/export-wins-ui#2]
When browsing `/wins/review/win-id/`, the page errors.

This is because the ui server cannot make any request to the data as it does not have any tokens.
You probably haven't noticed it because you are logged in as win creator so you're sharing the same cookies.
To reproduce it, create a `win`, go to the review url, copy it and open it in a different browser

**Comment by danielquinn** [comment]
Actually I noticed this this morning :-)  It's a problem because one of the requirements is that we allow customers to see a small portion of a win in order to verify its data, so the standard authentication of "no one can see this unless they're logged in" has to be relaxed to be something like pointing the form at another service that has lower security requirements and smaller portions of the data.

This should be done today I think.

**Comment by danielquinn** [comment]
This is resolved in #7.
